### ISSUE TITLE
Point array needs to be added to BattleshipModel class

### ISSUE THREAD

**Issue by TrevorSpear** [OSU-CS361-W17/group6_project1#17]
We need to add to BattleshipModel:
Point[] PlayerMisses;
Point[] PlayerHits;

Point[] ComputerMisses;
Point[] ComputerHits;

**Comment by evan-milton** [comment]
It's in but we need to get the function that supports adding to the array finished

**Comment by evan-milton** [comment]
EITHER:

Use arrays and get them working OR switch to a vector/dynamic array class

**Comment by TrevorSpear** [comment]
Used arrayList
Works really great. Look at the TestBattleShip to see it work and how to access it.
