### ISSUE TITLE
BattleshipModel needs to be filled out

### ISSUE THREAD

**Issue by TrevorSpear** [OSU-CS361-W17/group6_project1#2]
BattleshipModel needs setters and getters.
BattleshipModel needs ints and strings

Variables needed:
String- for name
int- size and location coordinates

**Comment by evan-milton** [comment]
I'll cover the BattleshipModel class and I'll write tests for it. Let me know if anything else is needed as we go.

**Comment by TrevorSpear** [comment]
Ok

**Comment by evan-milton** [comment]
I'm updating this and making a ship class. I can update the point class if needed. Let me know if you guys want me to add anything to these classes.

**Comment by evan-milton** [comment]
Almost done, gonna close this.
