### ISSUE TITLE
setLength() in ship.java

### ISSUE THREAD

**Issue by TrevorSpear** [OSU-CS361-W17/group6_project1#30]
Make sure we keep this. 
There was a comment saying:  // shouldn't need to resize an existing ship, but here it is
It's so that we we don't fail encapsulation.

**Comment by TrevorSpear** [comment]
When we create a ship we do setLength( length ) so we do use this. And this is on line #66 for Ship.java

**Comment by evan-milton** [comment]
we use it when creating ships, so good catch. resolving this
