### ISSUE TITLE
The program does not run at the current state

### ISSUE THREAD

**Issue by orrelln** [OSU-CS361-W17/group6_project1#5]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

This error code appears, and all attempts to fix it have failed.

**Comment by TrevorSpear** [comment]
We need to talk to the professor during office hours.

**Comment by evan-milton** [comment]
Meeting her @ 16:00. Join me.

**Comment by amedeekirk** [comment]
Seems to be an issue with the dependencies. Lets bring that up during the office hours

**Comment by evan-milton** [comment]
Don't worry bout it
